apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositevpcs.demo.anthos.com
spec:
  group: demo.anthos.com
  names:
    kind: CompositeVPC
    plural: compositevpcs
  claimNames: # this is what namespace scoped XRCs are called
    kind: CVPC
    plural: cvpcs
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                description: VPC configs.
                properties:
                  managementPolicy:
                    type: string
                    default: FullControl #ObserveOnly
                  location:
                    type: string
                  user:
                    type: string
                type: object
          status:
            type: object
            description: Status of VPC.
            properties:
              vpcId:
                type: string
              vpcId2:
                type: string
              subnetId:
                type: string
              region:
                type: string
    additionalPrinterColumns:
    - name: VPC1
      type: string
      jsonPath: ".status.vpcId"
    - name: VPC2
      type: string
      jsonPath: ".status.vpcId2"
    - name: SUBNET1
      type: string
      jsonPath: ".status.subnetId"

