#example of making an Attached EKS on AWS cluster
#note region us-east-1 is hard coded in the cluster, auth, nodepools, and vpc/subnets
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-vpc
  labels:
    crossplane.io/xrd: compositevpcs.demo.anthos.com
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeVPC
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: vpc
    base:
      apiVersion: ec2.aws.gke.cloud.google.com/v1beta1
      kind: VPC
      metadata:
        name: sample-vpc
        annotations:
          templatestacks.crossplane.io/deletion-priority: "2"
      spec:
        forProvider:
          cidrBlock: 10.0.0.0/16
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.user
      toFieldPath: spec.forProvider.tags["Name"]
      transforms:
      - type: string
        string:
          fmt: "%s-vpc"
    - type: FromCompositeFieldPath
      fromFieldPath: status.vpcId2
      toFieldPath: spec.forProvider.tags["Other"]
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.vpcId
  - name: vpc2
    base:
      apiVersion: ec2.aws.gke.cloud.google.com/v1beta1
      kind: VPC
      metadata:
        name: sample-vpc-2
        annotations:
          templatestacks.crossplane.io/deletion-priority: "1"
      spec:
        forProvider:
          cidrBlock: 10.0.0.0/16
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.user
      toFieldPath: spec.forProvider.tags["Name"]
      transforms:
      - type: string
        string:
          fmt: "%s-vpc-2"
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.vpcId2
  - name: subnet-a
    base:
      apiVersion: ec2.aws.gke.cloud.google.com/v1beta1
      kind: Subnet
      metadata:
        name: subnet-nodepool-1a
        labels:
          zone: us-east-1a
          access: public
      spec:
        forProvider:
          cidrBlock: 10.0.1.0/24
          vpcIdSelector:
            matchControllerRef: true
          mapPublicIpOnLaunch: true
          tags:
            Name: subnet-nodepool-a
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.availabilityZone
      transforms:
      - type: string
        string:
          fmt: "%sa"
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.subnetId